/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.emg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Proposal service. Represents a row in the &quot;EuroMillionGame_Proposal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.emg.model.impl.ProposalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.emg.model.impl.ProposalImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see Proposal
 * @see net.sareweb.emg.model.impl.ProposalImpl
 * @see net.sareweb.emg.model.impl.ProposalModelImpl
 * @generated
 */
public interface ProposalModel extends BaseModel<Proposal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposal model instance should use the {@link Proposal} interface instead.
	 */

	/**
	 * Returns the primary key of this proposal.
	 *
	 * @return the primary key of this proposal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposal.
	 *
	 * @param primaryKey the primary key of this proposal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proposal ID of this proposal.
	 *
	 * @return the proposal ID of this proposal
	 */
	public long getProposalId();

	/**
	 * Sets the proposal ID of this proposal.
	 *
	 * @param proposalId the proposal ID of this proposal
	 */
	public void setProposalId(long proposalId);

	/**
	 * Returns the draw ID of this proposal.
	 *
	 * @return the draw ID of this proposal
	 */
	public long getDrawId();

	/**
	 * Sets the draw ID of this proposal.
	 *
	 * @param drawId the draw ID of this proposal
	 */
	public void setDrawId(long drawId);

	/**
	 * Returns the email address of this proposal.
	 *
	 * @return the email address of this proposal
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this proposal.
	 *
	 * @param emailAddress the email address of this proposal
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the number1 of this proposal.
	 *
	 * @return the number1 of this proposal
	 */
	public int getNumber1();

	/**
	 * Sets the number1 of this proposal.
	 *
	 * @param number1 the number1 of this proposal
	 */
	public void setNumber1(int number1);

	/**
	 * Returns the number2 of this proposal.
	 *
	 * @return the number2 of this proposal
	 */
	public int getNumber2();

	/**
	 * Sets the number2 of this proposal.
	 *
	 * @param number2 the number2 of this proposal
	 */
	public void setNumber2(int number2);

	/**
	 * Returns the number3 of this proposal.
	 *
	 * @return the number3 of this proposal
	 */
	public int getNumber3();

	/**
	 * Sets the number3 of this proposal.
	 *
	 * @param number3 the number3 of this proposal
	 */
	public void setNumber3(int number3);

	/**
	 * Returns the number4 of this proposal.
	 *
	 * @return the number4 of this proposal
	 */
	public int getNumber4();

	/**
	 * Sets the number4 of this proposal.
	 *
	 * @param number4 the number4 of this proposal
	 */
	public void setNumber4(int number4);

	/**
	 * Returns the number5 of this proposal.
	 *
	 * @return the number5 of this proposal
	 */
	public int getNumber5();

	/**
	 * Sets the number5 of this proposal.
	 *
	 * @param number5 the number5 of this proposal
	 */
	public void setNumber5(int number5);

	/**
	 * Returns the star1 of this proposal.
	 *
	 * @return the star1 of this proposal
	 */
	public int getStar1();

	/**
	 * Sets the star1 of this proposal.
	 *
	 * @param star1 the star1 of this proposal
	 */
	public void setStar1(int star1);

	/**
	 * Returns the star2 of this proposal.
	 *
	 * @return the star2 of this proposal
	 */
	public int getStar2();

	/**
	 * Sets the star2 of this proposal.
	 *
	 * @param star2 the star2 of this proposal
	 */
	public void setStar2(int star2);

	/**
	 * Returns the type of this proposal.
	 *
	 * @return the type of this proposal
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this proposal.
	 *
	 * @param type the type of this proposal
	 */
	public void setType(String type);

	/**
	 * Returns the statistical population of this proposal.
	 *
	 * @return the statistical population of this proposal
	 */
	public long getStatisticalPopulation();

	/**
	 * Sets the statistical population of this proposal.
	 *
	 * @param statisticalPopulation the statistical population of this proposal
	 */
	public void setStatisticalPopulation(long statisticalPopulation);

	/**
	 * Returns the winnings of this proposal.
	 *
	 * @return the winnings of this proposal
	 */
	public float getWinnings();

	/**
	 * Sets the winnings of this proposal.
	 *
	 * @param winnings the winnings of this proposal
	 */
	public void setWinnings(float winnings);

	/**
	 * Returns the create date of this proposal.
	 *
	 * @return the create date of this proposal
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this proposal.
	 *
	 * @param createDate the create date of this proposal
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this proposal.
	 *
	 * @return the modify date of this proposal
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this proposal.
	 *
	 * @param modifyDate the modify date of this proposal
	 */
	public void setModifyDate(Date modifyDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Proposal proposal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Proposal> toCacheModel();

	@Override
	public Proposal toEscapedModel();

	@Override
	public Proposal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}